---
- name: "Install MySQL dependencies"
  apt: name={{ item }} update_cache=yes state=latest
  with_items:

    - python3-mysqldb
    - mariadb-client-10.0

# Manage Piwik database
- name: "Manage Piwik db"
  action: mysql_db encoding=utf8 name={{ mysql_piwik_db }} state=present login_user={{ mysql_admin_user }} login_password={{ mysql_admin_pass }} login_host={{ mysql_host }}

# Manage Piwik database user
- name: "Manage Piwik db-user"
  action: mysql_user name={{ mysql_piwik_user}} host=% password={{ mysql_piwik_pass}} priv={{ mysql_piwik_db}}.*:ALL state=present login_user={{ mysql_admin_user }} login_password={{ mysql_admin_pass }} login_host={{ mysql_host }}
