---
services: docker

env:
#  - distro: centos7
#    playbook: test.yml
#  - distro: centos6
#    playbook: test.yml
#  - distro: debian8
#    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
#  - distro: ubuntu1404
#    playbook: test.yml


before_install:

  - docker pull mysql
  - docker pull redis

  - docker run --name mysql -e MYSQL_ROOT_PASSWORD=000 -d mysql
  - docker run --name redis -d redis


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_idempotence=false
  - export linked_containers="--link redis:redis --link mysql:mysql"

  # Chmod test shim.
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check to make sure we can reach Piwik's homepage.
  - >
    sudo docker exec --tty ${container_id} env TERM=xterm curl localhost
    | grep -q 'piwikApp'
    && (echo 'Piwik installed successfully' && exit 0)
    || (echo 'Piwik installed unsuccessfully' && exit 1)

  # Check to make sure we can query reporting API.
  - >
    sudo docker exec --tty ${container_id} env TERM=xterm curl "localhost/index.php?module=API&method=VisitsSummary.get&idSite=1&period=day&date=today&format=JSON&token_auth=c449fb552e7d39fe6ae22d8a02f30e1a"
    | grep -q 'avg_time_on_site'
    && (echo 'Authenticated to API successfully' && exit 0)
    || (echo 'Authenticated to API unsuccessfully' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
