# Install Piwik dependencies
- name: Add repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: "Install PHP dependencies"
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - 'php7.1'
    - 'php7.1-mysql'
    - 'php7.1-gd'
    - 'php7.1-geoip'
    - 'php7.1-ldap'
    - 'php7.1-fpm'
    - 'php7.1-cli'
    - 'php7.1-mbstring'
    - 'php7.1-xml'

- name: Configure php-fpm php.ini
  template:
    src: php-fpm.ini.j2
    dest: /etc/php/7.1/fpm/php.ini

- name: Configure php-fpm www.conf
  template:
    src: php-fpm-www.conf.j2
    dest: /etc/php/7.1/fpm/pool.d/www.conf

- name: Restart PHP FPM
  shell: service php7.1-fpm restart
